## Sara Aldubaie 

In [2]:
#package numpy 
import numpy as np

In [4]:
A = np.random.rand(2,3) # 2 number of row 3 number of column
print(A)

[[0.43316186 0.6200794  0.90272544]
 [0.75116152 0.31958424 0.2828003 ]]


In [12]:
A = np.random.randn(2,2) # 
print(A)

[[ 0.16379146 -0.83871359]
 [ 0.51274693  0.11853901]]


In [13]:
 A = np.random.randint(2,5,6) #2 low, 5 high, 6 size
 print(A)

[3 3 3 4 3 3]


In [26]:
np.random.choice([1,20,3,6,7], 3)

array([ 7,  7, 20])